"""add

Revision ID: 82ca763c7321
Revises: 37b7b076d2ee
Create Date: 2026-02-10 20:12:01.018916

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82ca763c7321"
down_revision: Union[str, Sequence[str], None] = "37b7b076d2ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("surveys", sa.Column("users_incl", sa.Text(), nullable=True))
    op.add_column("surveys", sa.Column("users_excl", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveys", "users_excl")
    op.drop_column("surveys", "users_incl")
    # ### end Alembic commands ###
