"""

Revision ID: f15d956d1043
Revises: 82ca763c7321
Create Date: 2026-02-14 03:27:23.228103

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f15d956d1043"
down_revision: Union[str, Sequence[str], None] = "82ca763c7321"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "survey_sent_messages",
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("receiver_slack_id", sa.String(length=50), nullable=False),
        sa.Column("message_ts", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slack_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["survey_id"],
            ["surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("survey_sent_messages")
    # ### end Alembic commands ###
