"""Add user lists

Revision ID: 0911d89b7f9d
Revises: dac0507e3b5d
Create Date: 2026-02-04 00:22:44.348048

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0911d89b7f9d"
down_revision: Union[str, Sequence[str], None] = "dac0507e3b5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_lists",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slack_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "survey_user_lists",
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("user_list_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["survey_id"],
            ["surveys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_list_id"],
            ["user_lists.id"],
        ),
        sa.PrimaryKeyConstraint("survey_id", "user_list_id"),
    )
    op.create_table(
        "user_list_members",
        sa.Column("user_list_id", sa.Integer(), nullable=False),
        sa.Column("slack_id", sa.String(length=50), nullable=False),
        sa.Column("user_name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_list_id"],
            ["user_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_list_id", "slack_id", name="uq_user_list_member"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_list_members")
    op.drop_table("survey_user_lists")
    op.drop_table("user_lists")
    # ### end Alembic commands ###
