"""add survey and survey_response table

Revision ID: dac0507e3b5d
Revises: 8592e3e25d92
Create Date: 2026-01-31 22:38:09.205950

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dac0507e3b5d"
down_revision: Union[str, Sequence[str], None] = "8592e3e25d92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "surveys",
        sa.Column("survey_name", sa.String(length=255), nullable=False),
        sa.Column("owner_slack_id", sa.String(length=50), nullable=False),
        sa.Column("owner_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slack_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "survey_responses",
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("responder_slack_id", sa.String(length=50), nullable=False),
        sa.Column("responder_name", sa.String(length=255), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slack_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["survey_id"],
            ["surveys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("survey_responses")
    op.drop_table("surveys")
    # ### end Alembic commands ###
