"""add survey text

Revision ID: 6fad2049bd07
Revises: dac0507e3b5d
Create Date: 2026-02-04 01:54:05.465832

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fad2049bd07"
down_revision: Union[str, Sequence[str], None] = "dac0507e3b5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveys",
        sa.Column("survey_text", sa.Text(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveys", "survey_text")
    # ### end Alembic commands ###
