"""delete_email_field

Revision ID: 8592e3e25d92
Revises: 7357facf0367
Create Date: 2026-01-28 19:56:43.332719

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8592e3e25d92"
down_revision: Union[str, Sequence[str], None] = "7357facf0367"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slack_users_email"), table_name="slack_users")
    op.drop_column("slack_users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_users",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_slack_users_email"), "slack_users", ["email"], unique=True)
    # ### end Alembic commands ###
